### ISSUE TITLE
Support different encodings

### ISSUE THREAD

**Issue by luber** [alexcaza/export-to-csv#23]
Currently generated csv file is in UTF-8 or UTF-8 with BOM encoding (default).
This produces problems with determining negative float values when opening in MS Excel. It treats negative values as a text with a dash symbol instead of float value with minus...
When I manually converted file to ASCII encoding - it opens in MS Excel correctly.
So it would be great if I can set file encoding in export-to-csv options

**Comment by alexcaza** [comment]
This no longer seems to be an issue with Excel version 16.77.1 (23091703). Negative numbers appear to behave as numbers, and not text with a dash symbol.

Here's a screenshot of the version of Excel mentioned with negative numbers from a test CSV generated using this library.
![Screenshot of MS Excel with output from export-to-csv integration test](https://s.alexcaza.com/Screen-Shot-2023-10-08-20-16-56.50-1696810622.png)

I did look into supporting multiple encodings and I think it's out-of-scope for this library. At least for now.  With`utf-8` being the modern standard, and javascript in the browser not really offering ergonomic ways to change the encoding of strings (AFAIK), I'm not really keen on implementing this right now. If it becomes a requested enough feature, I might spend more time investigating it.

In the meantime, for anyone coming across this, [papaparse](https://www.papaparse.com/docs#config) seems to offer different encodings. Though I haven't tested this out myself, it might be worth looking into instead of waiting for this library to support this feature 😄
