### ISSUE TITLE
Dynamic data getting only first column.

### ISSUE THREAD

**Issue by shashankrepo** [alexcaza/export-to-csv#31]
if I have two rows like this,
```
const abc = [
{u1:'U', p1: 'R' },
{u1:'L', p1:'K', u2:'S', p2:'T'}
]
```

It gives result like this

u1   p1
U    R
L    K

but it should be 

u1    p1    u2    p2
U     R     
L      K      S     T

**Comment by Shannanigans** [comment]
I have the same issue, even after explicitly specifying the headers in options.

I have time-series data for which various parameters are not guaranteed to have values on every row and are by default omitted. This results in a csv with fewer columns than there should be.

I can process the data so that the keys are represented instead of being omitted, but strictly speaking, this should not be necessary, especially if we explicitly specify the headers. 

Perhaps the issue can be addressed via a header key mapping? If provided the number of columns are explicitly defined with the expected keys with their associated labels. Any additional data can be ignored.
```javascript
header: {
    'column_key': 'display_label'
}
```

https://github.com/alexcaza/export-to-csv/issues/11 Appears to me to further confound the column key resolution issue.
