### ISSUE TITLE
',' separator not being recognised

### ISSUE THREAD

**Issue by diez-esteban** [alexcaza/export-to-csv#36]
Hi everyone!

I'm coming across an issue where the exported csv is not properly formatted. Looks like excel doesn't recognise the "," as the field separator. It has happened to users both using win and macos. Checked their regional config and all seems to be alright. 

![image](https://user-images.githubusercontent.com/51055993/104932723-f9af6800-5975-11eb-9e34-ddeaa62cc3b8.png)

Here's the params I'm passing to export-to-csv. Am I missing any details in the config? Thank you.

![image](https://user-images.githubusercontent.com/51055993/104932556-c1a82500-5975-11eb-8e61-5064f64d9358.png)

**Comment by bergamin** [comment]
@diez-esteban and @alexcaza, this is a bug in export-to-csv. I didn't see this issue before creating mine, but here is what's going on: #43

**Comment by rtkirill** [comment]
Any updates on this bug?

**Comment by bergamin** [comment]
@diez-esteban just to add to this, this happens because Excel in Spanish probably uses `,` as a decimal separator and because of that, it would use by default `;` as a column separator. At least that's what happens in Excel in Portuguese.

To force Excel to accept a specific separator character, in your example `,`, the first line of the file should be `sep=,`. @alexcaza, this is what's missing here. This seems not to be only Excel. I've seen other software require the `sep` keyword before

BTW, I tried the v1.0.0 you published and this bug is still present (I had a few other problems too, but I'll test it more before opening issues).

I came up with a way to work around this. You can use the `title` and `showTitle` parameters and add `sep=,` through it. It will render a blank line as first line, though

**Comment by BenjaminHoch-GoTo** [comment]
We had an issue with users using different regional settings on their systems (mac and windows), and having fieldSeparator: ';' in our config. So bascially semi-colon only worked as delimiter for systems which use number formats "1.234.567,89".
With changing the config to :
```
...
fieldSeparator: ',',
showTitle: true,
title: 'sep=,\n',
...
```

we were able to get it to work on all systems/settings we tested it on and Excel opened the csv file properly

**Comment by alexcaza** [comment]
Thanks for digging into this, @bergamin and @BenjaminHoch-GoTo!

This doesn't seem to be a standardized feature of CSVs, just something that some editors support. This is going off this [StackExchange Q&A](https://superuser.com/questions/773644/what-is-the-sep-metadata-you-can-add-to-csvs) and [RFC 4180](https://www.rfc-editor.org/rfc/rfc4180) (which doesn't mention this metadata at all).

I know I stated in the new README that this library isn't aiming to be 100% compliant with the spec, however, I'm weary of bloating the already-not-super-clear-API with another property or overloading an existing property. The goal of this library is to be small, simple and clear.

Since there's a work-around using `title` for now, I'll spend a bit more time thinking on this before committing to anything 😄 I'm very open to ideas! Especially since I don't interact with this library on a daily basis anymore.

**Comment by BenjaminHoch-GoTo** [comment]
the workaround is fine if you don't use special characters (different languages) in your csv files, because once you add the "sep=," prop to the title, Excel does not respect the utf-8 format anymore. Since we also support more than english files, the workaround doesn't work for us anymore.

**Comment by alexcaza** [comment]
There doesn't seem to be a clean workaround for the UTF-8 BOM + using `,` as a separator with Excel in locales that use `,` for numbers.

I'm going to close this issue for now since respecting UTF-8 encoding and `sep=` isn't something the library can influence within Excel, and because there's a basic workaround.

I'd maybe recommend checking out alternative libraries in the meantime, in case they better deal with these cases. A few alternatives can be found here: https://github.com/alexcaza/export-to-csv#alternatives
