### ISSUE TITLE
How to parse nested JSON properties?

### ISSUE THREAD

**Issue by sdancer75** [alexcaza/export-to-csv#75]
Is there any way to parse nested JSON properties ? Currently, it shows them as [OBJECT]

```
         {
            name: 'Rouky',
            date: '2023-09-01',
            percentage: 0.4,
            quoted: '"Pickles"',
            Service: {
               active: 'yes',
               limit: 1,
            },
         },
```

**Comment by alexcaza** [comment]
Could you elaborate on what output you'd like from this input? How do you see nested properties being rendered in a CSV file?

The CSV spec doesn't support nested columns, which I'll not support in this library since the output is too ambiguous.

However, If you want something like the below as output:
```csv
name, Service, quoted
Rouky, active: yes | limit: 1, "Pickles"
```
You could transform the data before passing it to the data generator with something like:
```typescript
let data = {
  name: 'Rouky',
  date: '2023-09-01',
  percentage: 0.4,
  quoted: '"Pickles"',
  Service: {
    active: 'yes',
    limit: 1,
  },
}
data.Service = `active: ${data.Service.active} | limit: ${data.Service.limit}`;
generateCsv(csvConfig)(data);
```

**Comment by alexcaza** [comment]
I'm going to close this issue for now. Feel free to open a [discussion under ideas](https://github.com/alexcaza/export-to-csv/discussions/categories/ideas) on how to handle nested properties if you feel strongly about this feature being something the library should handle.

I'm not keen on adding it to the library since it's pretty easy to transform the data before you pass it in. But if someone has a suggestion for a clean API or obvious use-cases, I'm all ears 😄
